version: '3.5'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    ports:
    - "80:3000"
    command: npm start 
  backend:
    container_name: backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 
    build: ./backend
    restart: always
    ports:
    - "8000:8000"
 